AWSTemplateFormatVersion: '2010-09-09'
Description: 'Healthcare Telemedicine AI - Infrastructure Stack'

Parameters:
  Environment:
    Type: String
    Default: development
    AllowedValues:
      - development
      - staging
      - production
    Description: Deployment environment

  ProjectName:
    Type: String
    Default: telemedicine-ai
    Description: Project name for resource naming

Resources:
  # ============== KMS Key ==============
  EncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Encryption key for telemedicine data
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  EncryptionKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub 'alias/${ProjectName}-key'
      TargetKeyId: !Ref EncryptionKey

  # ============== DynamoDB Tables ==============
  PatientsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-patients-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: patient_id
          AttributeType: S
      KeySchema:
        - AttributeName: patient_id
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref EncryptionKey
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment

  SessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-sessions-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: session_id
          AttributeType: S
        - AttributeName: patient_id
          AttributeType: S
      KeySchema:
        - AttributeName: session_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: patient-index
          KeySchema:
            - AttributeName: patient_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref EncryptionKey
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment

  AssessmentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-assessments-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: assessment_id
          AttributeType: S
        - AttributeName: patient_id
          AttributeType: S
      KeySchema:
        - AttributeName: assessment_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: patient-index
          KeySchema:
            - AttributeName: patient_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref EncryptionKey
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment

  ConversationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-conversations-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: session_id
          AttributeType: S
        - AttributeName: message_id
          AttributeType: S
      KeySchema:
        - AttributeName: session_id
          KeyType: HASH
        - AttributeName: message_id
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref EncryptionKey
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # ============== S3 Bucket ==============
  DocumentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-documents-${Environment}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref EncryptionKey
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 90
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # ============== SNS Topic ==============
  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-alerts-${Environment}'
      KmsMasterKeyId: !Ref EncryptionKey
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # ============== IAM Role for Lambda ==============
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-lambda-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: TelemedicinePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !GetAtt PatientsTable.Arn
                  - !GetAtt SessionsTable.Arn
                  - !GetAtt AssessmentsTable.Arn
                  - !GetAtt ConversationsTable.Arn
                  - !Sub '${PatientsTable.Arn}/index/*'
                  - !Sub '${SessionsTable.Arn}/index/*'
                  - !Sub '${AssessmentsTable.Arn}/index/*'
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub '${DocumentsBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                Resource: '*'
              - Effect: Allow
                Action:
                  - comprehendmedical:DetectEntitiesV2
                  - comprehendmedical:InferICD10CM
                  - comprehendmedical:InferRxNorm
                Resource: '*'
              - Effect: Allow
                Action:
                  - textract:DetectDocumentText
                  - textract:AnalyzeDocument
                Resource: '*'
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref AlertTopic
              - Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:GenerateDataKey
                Resource: !GetAtt EncryptionKey.Arn
      Tags:
        - Key: Environment
          Value: !Ref Environment

Outputs:
  PatientsTableName:
    Description: Patients DynamoDB table name
    Value: !Ref PatientsTable
    Export:
      Name: !Sub '${ProjectName}-patients-table-${Environment}'

  SessionsTableName:
    Description: Sessions DynamoDB table name
    Value: !Ref SessionsTable
    Export:
      Name: !Sub '${ProjectName}-sessions-table-${Environment}'

  AssessmentsTableName:
    Description: Assessments DynamoDB table name
    Value: !Ref AssessmentsTable
    Export:
      Name: !Sub '${ProjectName}-assessments-table-${Environment}'

  ConversationsTableName:
    Description: Conversations DynamoDB table name
    Value: !Ref ConversationsTable
    Export:
      Name: !Sub '${ProjectName}-conversations-table-${Environment}'

  DocumentsBucketName:
    Description: Documents S3 bucket name
    Value: !Ref DocumentsBucket
    Export:
      Name: !Sub '${ProjectName}-documents-bucket-${Environment}'

  AlertTopicArn:
    Description: Alert SNS topic ARN
    Value: !Ref AlertTopic
    Export:
      Name: !Sub '${ProjectName}-alert-topic-${Environment}'

  LambdaRoleArn:
    Description: Lambda execution role ARN
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: !Sub '${ProjectName}-lambda-role-${Environment}'

  EncryptionKeyArn:
    Description: KMS encryption key ARN
    Value: !GetAtt EncryptionKey.Arn
    Export:
      Name: !Sub '${ProjectName}-encryption-key-${Environment}'
