apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-minimal-starter
  namespace: genai-minimal-starter
  labels:
    app.kubernetes.io/name: genai-minimal-starter
    app.kubernetes.io/component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: genai-minimal-starter
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: genai-minimal-starter
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: api
        image: genai-minimal-starter:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: genai-minimal-starter-config
              key: APP_NAME
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: genai-minimal-starter-config
              key: APP_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: genai-minimal-starter-config
              key: PORT
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
